apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: pingpong-keys
  namespace: pingpong
  annotations:
    secrets-store.csi.k8s.io/used-by: "pingpong"
    secrets-store.csi.k8s.io/enable-secret-rotation: "true"
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "a38c3679-7db0-4560-857b-6d7c4b451bbb"
    keyvaultName: ping-pong-vault-keys
    tenantId: e3c32f4f-ea7b-483e-98a6-8d144c002ad8
    cloudName: ""
    objects: |
      array:
        - |
          objectName: rsa-public-key
          objectType: secret
        - |
          objectName: rsa-private-key
          objectType: secret
  secretObjects:                  
  - secretName: pingpong-keys-secret
    type: Opaque
    data:
    - objectName: rsa-public-key
      key: rsa-public-key
    - objectName: rsa-private-key
      key: rsa-private-key
