apiVersion: apps/v1
kind: Deployment
metadata:
  name: webservice
  namespace: pingpong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webservice
  template:
    metadata:
      labels:
        app: webservice
    spec:
      containers:
      - name: webservice
        image: pingpongacr333.azurecr.io/webservice:latest
        ports:
        - containerPort: 8080
        env:
        - name: RSA_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: pingpong-keys-secret
              key: rsa-public-key
        - name: REDIS_HOST
          value: "redis-pingpong-cache"
        - name: REDIS_PORT
          value: "6379"
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: pingpong-keys
